version: '3.8'

services:

  web:
    build: .
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0:8000"
    command: bash -c "python manage.py runserver 0:8000"
    #command: python /code/manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    container_name: web
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-w0at3z!v!*8m7@5!*(sobyhv@!baf2r$$^)g_=56!oen!hds9g+"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
    networks:
      - mynetwork

  db:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
